/**
 * Expo plugin to automatically generate android/local.properties with Android SDK path
 * This file is auto-generated and should not be committed
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

/**
 * Detects Android SDK location from common locations or environment variables
 */
function detectAndroidSdkPath() {
  // Try ANDROID_HOME first
  if (process.env.ANDROID_HOME) {
    return process.env.ANDROID_HOME;
  }

  // Try ANDROID_SDK_ROOT
  if (process.env.ANDROID_SDK_ROOT) {
    return process.env.ANDROID_SDK_ROOT;
  }

  // Try common default locations
  const homeDir = os.homedir();
  const platform = os.platform();

  const commonPaths = [];

  if (platform === 'darwin') {
    // macOS
    commonPaths.push(
      path.join(homeDir, 'Library', 'Android', 'sdk'),
      path.join(homeDir, '.android', 'sdk')
    );
  } else if (platform === 'win32') {
    // Windows
    const localAppData =
      process.env.LOCALAPPDATA || path.join(homeDir, 'AppData', 'Local');
    commonPaths.push(
      path.join(localAppData, 'Android', 'Sdk'),
      path.join(
        process.env.PROGRAMFILES || 'C:\\Program Files',
        'Android',
        'android-sdk'
      )
    );
  } else {
    // Linux
    commonPaths.push(
      path.join(homeDir, 'Android', 'Sdk'),
      path.join(homeDir, '.android', 'sdk'),
      '/opt/android-sdk',
      '/usr/lib/android-sdk'
    );
  }

  // Check if any of the common paths exist
  for (const sdkPath of commonPaths) {
    if (fs.existsSync(sdkPath)) {
      return sdkPath;
    }
  }

  return null;
}

/**
 * Generates android/local.properties file with SDK path
 */
function generateLocalProperties(projectRoot) {
  const localPropertiesPath = path.join(
    projectRoot,
    'android',
    'local.properties'
  );
  const androidDir = path.join(projectRoot, 'android');

  // Ensure android directory exists
  if (!fs.existsSync(androidDir)) {
    return;
  }

  const sdkPath = detectAndroidSdkPath();

  if (!sdkPath) {
    console.warn(
      '⚠️  Android SDK path not found. Please set ANDROID_HOME environment variable.'
    );
    console.warn(
      '   Or create android/local.properties manually with: sdk.dir=/path/to/android/sdk'
    );
    return;
  }

  // Normalize path separators for Windows
  const normalizedPath = sdkPath.replace(/\\/g, '/');

  const content = `# This file is auto-generated by Expo plugin
# Do not edit manually - it will be regenerated during prebuild
sdk.dir=${normalizedPath}
`;

  fs.writeFileSync(localPropertiesPath, content, 'utf8');
  // console.log(`✅ Generated android/local.properties with SDK path: ${normalizedPath}`);
}

const withAndroidLocalProperties = (config) => {
  // Generate local.properties during prebuild
  const projectRoot = config._internal?.projectRoot || process.cwd();

  try {
    generateLocalProperties(projectRoot);
  } catch (error) {
    console.warn(
      '⚠️  Failed to generate android/local.properties:',
      error.message
    );
  }

  return config;
};

module.exports = withAndroidLocalProperties;
